import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useLayoutEffect, useEffect, useState } from "react";
import styled from "styled-components";
import Block from "../components/Block";
import Link from "next/link";
import { instance } from "../utils/instance";
import { Props } from "../types/type";

function Home() {
  const [posts, setPosts] = useState<Props[]>([]);

  useLayoutEffect(() => {
    const checkLogin = () => {
      if (localStorage.getItem("token") === null) {
        location.href = "/Signup";
      }
    };
    checkLogin();
  }, []);

  useEffect(() => {
    const jwt = localStorage.getItem("token");
    instance.get(
      "/users/@me", {
        headers: {
          Authorization: `Bearer ${jwt}`,
        }
      }
    ).then((res) => {
      localStorage.setItem("user_id", res.data.id)
      instance.get("/posts", {
        headers: {
          Authorization: `Bearer ${jwt}`,
        },
      }).then((res) => setPosts(res.data));
    })
  }, []);
  return (
    <div>
      <Head>
        <title>OnakaSNS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostIco>
        <Link href="/Edit">
          <input type="image" src="edit.svg" />
        </Link>
      </PostIco>
      <BG>
        <Entire>
          <CenterSection>
            {posts.map((e) => {
              return (
                <BlockLine key={e.id}>
                  <Block props={e} />
                </BlockLine>
              );
            })}
          </CenterSection>
        </Entire>
      </BG>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
export default Home;

const BG = styled.div`
  background-color: #fe9600;
  background-size: cover;
  display: flex;
  justify-content: center;
  min-height: 100vh;
  height: 100%;
`;

const Entire = styled.div`
  display: flex;
  justify-content: center;
`;

const CenterSection = styled.div`
  width: 800px;
  min-height: 100vh;
  background-color: #ffee4a;
`;

const BlockLine = styled.div`
  text-align: center;
  display: flex;
  justify-content: center;
`

const PostIco = styled.div`
  left: 30px;
  top: 30px;
  position: absolute;
  background-color: #bbb;
  height: 60px;
  width: 60px;
  padding: 5px;
  border-radius: 30px;
  display: flex;
  align-content: center;
  justify-content: center;
`

// .color-0 { color: #fe9600; }
// .color-1 { color: #ffc501; }
// .color-2 { color: #ffee4a; }
// .color-3 { color: #77477e; }
// .color-4 { color: #03001c; }
